# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./ .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir paho-mqtt pymongo redis

# Run the MQTT subscriber script
CMD ["python", "subscriber.py"]
